### ISSUE TITLE
vcd file 

### ISSUE THREAD

**Issue by ferdous313** [ccelio/boom-template#24]
I am trying to debug a design. 
I am using this to get the vpd file and change it to vcd file using vpd2vcd. 
/mada/users/nferdous/boom-template/verisim/simulator-boom.system-BoomConfig-debug  +max-cycles=10000000  +verbose -voutput/dhrystone.riscv.vpd  output/dhrystone.riscv 3>&1 1>&2 2>&3 | /mada/software/riscv/bin/spike-dasm  > output/dhrystone.riscv.out && [ $PIPESTATUS -eq 0 ]
However, The vpdfile is not converted to vcd (although the vpd in the rocket chip is working good). Please let me know how I can get the vcd file instead of vpd.

**Comment by ccelio** [comment]
I believe this is a flub in the Makefile: verilator's `-v` can only ever create `vcd` files, despite what the Makefile tried to call it. You can open the file in a text editor to verify that it's a readable value-change dump. 

For future issues, the main development is currently at (https://github.com/riscv-boom/boom-template).

**Comment by ferdous313** [comment]
Thanks!
