### ISSUE TITLE
How to merge this into fpga-zynq repo

### ISSUE THREAD

**Issue by usnull0000** [ccelio/boom-template#7]
I want to synthesize rocket-chip with BOOM cores on zedboard, but I can't find how to do that.

**Comment by ccelio** [comment]
I don't think there's currently any recommended way to do that.

In the past, I've used the following repositories (don't recall which branches are most up-to-date):

https://github.com/ucb-bar/fpga-zynq
https://github.com/donggyukim/fpga-zynq


The new boom-template repository is set up in the manner of the ucb-bar/project-template and sifive/freedom repositories, which may provide some guidance on putting together a self-hosted setup.

Finally, a zedboard is almost certainly not big enough. Not without turning off things like FP support or superscalar.
